INSERT INTO attractions (name, description, city, tags)
VALUES
('SMK', 'Statens museum for Kunst', 'København', 'Kunst,Museum'),
('Odense Zoo', 'Europas bedste zoo', 'Odense', 'Børnevenlig'),
('Dyrehaven', 'Naturpark med skovområder', 'Kongens Lyngby', 'Natur,Gratis'),
('Tivoli', 'Forlystelsespark i Københavns centrum', 'København', 'Børnevenlig,Forlystelser');

INSERT INTO cities (name) VALUES
('Aalborg'),
('Aabenraa'),
('Aalst'),
('Aars'),
('Addit'),
('Aarhus'),
('Bagsværd'),
('Ballerup'),
('Bramming'),
('Brøndby'),
('Børkop'),
('Børglum'),
('Christiansfeld'),
('Djursland'),
('Ebeltoft'),
('Esbjerg'),
('Faaborg'),
('Fredericia'),
('Frederikshavn'),
('Frederiksberg'),
('Fur'),
('Fåborg'),
('Gilleleje'),
('Gladsaxe'),
('Glostrup'),
('Guldborgsund'),
('Hadsten'),
('Haderslev'),
('Hammel'),
('Hedehusene'),
('Herfølge'),
('Herning'),
('Helsingør'),
('Hjørring'),
('Holbæk'),
('Holstebro'),
('Hornslet'),
('Ikast'),
('Ikast-Brande'),
('Jægerspris'),
('Jelling'),
('Kastrup'),
('Kerteminde'),
('Kolding'),
('Kongens Lyngby'),
('København'),
('Køge'),
('Landskrona'),
('Lemvig'),
('Middelfart'),
('Mors'),
('Næstved'),
('Nyborg'),
('Nykøbing Falster'),
('Nykøbing Mors'),
('Odder'),
('Odense'),
('Randers'),
('Ringe'),
('Ringsted'),
('Roskilde'),
('Skanderborg'),
('Skive'),
('Slagelse'),
('Snekkersten'),
('Søborg'),
('Sønderborg'),
('Sørum'),
('Svendborg'),
('Taastrup'),
('Thisted'),
('Tønder'),
('Varde'),
('Vejle'),
('Viborg'),
('Vojens'),
('Åbyhøj')
